/**
 * Single source of truth for every piece of copy on the site.
 *
 * BRANDING HIERARCHY (do not flatten this — see FEST below):
 *   1. ANVIKSHA '26 — THE EPOCH          the fest
 *   2. Digital Voyage: Charting the       the theme
 *      Course of Innovation
 *   3. "five eras of gaming, arcade       the VISUAL SYSTEM used to express
 *      to AI"                             the theme. Never billed as a theme.
 *
 * DATA GAPS: fields typed `| null` are awaiting real values. They are null on
 * purpose — every consumer omits the row entirely rather than printing "TBD".
 * Search this file for "NEEDS DATA" to find all of them.
 */

export type EraId = 1 | 2 | 3 | 4 | 5;

export type SceneKey =
  | 'captureTheFlag'
  | 'escapeTheServer'
  | 'bridgeWars'
  | 'algorithmAuction'
  | 'aiWhisperer'
  | 'techMinute'
  | 'techTunes'
  | 'parallelProtocol'
  | 'nexusNegotiator'
  | 'arrayPataHai'
  | 'secretSeekers'
  | 'valorant'
  | 'fifa'
  | 'mortalKombat'
  | 'tekken'
  | 'roboSoccer'
  | 'roboRace'
  | 'throughTheLens'
  | 'questToCinema'
  | 'interfaceQuest'
  | 'gameAthon';

export interface AnvikshaEvent {
  id: string;
  /** URL segment: /events/<slug>. Kept identical to `id`. */
  slug: string;
  name: string;
  tagline: string;
  blurb: string;
  scene: SceneKey;
  /** Short chip copy, e.g. "Teams of 3 · 120 min". Duration is parsed from it. */
  format: string;

  /* --- NEEDS DATA: supplied per event, null until then ------------------- */
  /** Full rule set, one string per bullet. */
  rules: string[] | null;
  /** Confirmed team size, e.g. "3–4 members". */
  teamSize: string | null;
  /** Confirmed prize for this event, in rupees. Feeds the prize pool section. */
  prize: number | null;
  /** Direct Unstop registration URL for this event. */
  unstopUrl: string | null;
}

export interface Era {
  id: EraId;
  key: string;
  label: string;
  years: string;
  category: string;
  headline: string;
  description: string;
  accent: string;
  events: AnvikshaEvent[];
}

/* Every event literal below omits the four gap fields; this fills them with
   null so the type stays honest without repeating `rules: null` 21 times. */
type EventSeed = Omit<AnvikshaEvent, 'slug' | 'rules' | 'teamSize' | 'prize' | 'unstopUrl'> &
  Partial<Pick<AnvikshaEvent, 'rules' | 'teamSize' | 'prize' | 'unstopUrl'>>;

const ev = (seed: EventSeed): AnvikshaEvent => ({
  slug: seed.id,
  rules: null,
  teamSize: null,
  prize: null,
  unstopUrl: null,
  ...seed,
});

export const FEST = {
  name: "ANVIKSHA '26",
  subtitle: 'The Epoch',

  /** The theme. The only thing that should ever be labelled "theme". */
  theme: 'Digital Voyage: Charting the Course of Innovation',

  /** Subtitle to the theme — the visual system, introduced once. */
  themeSubtitle: 'Charted across five eras of gaming, from arcade to AI.',

  /** Same idea in plain language, for the About section. */
  themePlain:
    'Innovation does not arrive all at once — it is charted, one leap at a time. Digital Voyage follows that route, and we tell it through the medium every engineer grew up with: five eras of gaming, from the first arcade cabinet to worlds generated by machines.',

  date: '12 September 2026',
  dateShort: '12.09.2026',
  /** Countdown target — 09:30 IST. */
  startsAtISO: '2026-09-12T09:30:00+05:30',
  /** Used only to switch the countdown from "Live Now" to "Concluded". */
  endsAtISO: '2026-09-12T18:30:00+05:30',

  venue: 'STME, NMIMS Chandigarh',
  venueShort: 'STME NMIMS Chandigarh',
  institute: 'School of Technology Management & Engineering',
  university: 'NMIMS Chandigarh',

  edition: '2026 edition',
  /** Previous editions, newest last. Drives the About copy. */
  pastEditions: ['2024', '2025'],
  cadence: 'Single-day',

  /* NEEDS DATA: master Unstop URL for the fest. Falls back to the on-page
     registration section until supplied. */
  registerUrl: '#register',

  brief:
    'One day. Five eras. ANVIKSHA 26 traces the arc of play from the phosphor glow of the first arcade cabinet to worlds generated on the fly by machines — and asks what engineers build next.',
} as const;

/** Referenced by both CONTACT and the FAQ copy — declared once, above both. */
const CONTACT_EMAIL = 'anviksha@nmims.edu.in';

export const ERAS: Era[] = [
  {
    id: 1,
    key: 'arcade',
    label: 'ERA 01',
    years: '1972 — 1985',
    category: 'Technical',
    headline: 'PHOSPHOR',
    description:
      'Blocky sprites, one screen, no save file. Pure logic under hard constraints — which is exactly what the technical track asks of you.',
    accent: '#39ff6a',
    events: [
      ev({
        id: 'capture-the-flag',
        name: 'Capture the Flag',
        tagline: 'Jeopardy-style security gauntlet',
        blurb:
          'Crack layered challenges across crypto, forensics and web exploitation. Every flag planted is points on the board.',
        scene: 'captureTheFlag',
        format: 'Teams of 3 · 120 min',
      }),
      ev({
        id: 'escape-the-server',
        name: 'Escape the Server',
        tagline: 'Locked in a rack, ticking clock',
        blurb:
          'A chained set of systems puzzles — logs, ports, permissions. Solve the sequence before the vault seals for good.',
        scene: 'escapeTheServer',
        format: 'Teams of 4 · 60 min',
      }),
      ev({
        id: 'bridge-wars',
        name: 'Bridge Wars',
        tagline: 'Load-bearing engineering under pressure',
        blurb:
          'Design, build and test a truss that survives the load run. Least material, most strength, wins.',
        scene: 'bridgeWars',
        format: 'Teams of 3 · 90 min',
      }),
      ev({
        id: 'algorithm-auction',
        name: 'Algorithm Auction',
        tagline: 'Bid for the code you need',
        blurb:
          'Spend a virtual purse on algorithm fragments, then assemble them into the fastest working solution. Bad bids cost you complexity.',
        scene: 'algorithmAuction',
        format: 'Teams of 2 · 75 min',
      }),
      ev({
        id: 'ai-whisperer',
        name: 'AI Whisperer',
        tagline: 'Prompt-craft as a competitive sport',
        blurb:
          'Given a target output, steer the model there in the fewest tokens. Precision beats verbosity every round.',
        scene: 'aiWhisperer',
        format: 'Solo · 45 min',
      }),
      ev({
        id: 'tech-minute-to-win-it',
        name: 'Tech Minute to Win It',
        tagline: 'Sixty seconds per station',
        blurb:
          'Rapid-fire micro-challenges: debug it, wire it, name it, ship it. The clock is the only judge that matters.',
        scene: 'techMinute',
        format: 'Solo · rolling heats',
      }),
    ],
  },
  {
    id: 2,
    key: 'cabinet',
    label: 'ERA 02',
    years: '1985 — 1998',
    category: 'E-Sports',
    headline: 'CABINET',
    description:
      'Neon cabinets, quarter-fed rivalries, the first crowds around a screen. The competitive instinct that built e-sports starts here.',
    accent: '#ff2e7e',
    events: [
      ev({
        id: 'valorant',
        name: 'Valorant',
        tagline: '5v5 tactical shooter',
        blurb: 'Standard competitive map pool, single-elimination bracket, BO1 until the semis.',
        scene: 'valorant',
        format: 'Teams of 5 · bracket',
      }),
      ev({
        id: 'fifa',
        name: 'FIFA',
        tagline: 'One-on-one on the pitch',
        blurb: 'Six-minute halves, no custom squads, golden goal in the knockouts.',
        scene: 'fifa',
        format: 'Solo · bracket',
      }),
      ev({
        id: 'mortal-kombat',
        name: 'Mortal Kombat',
        tagline: 'Best of three, no mercy',
        blurb: 'Blind character select, first to two rounds, winner stays on the stick.',
        scene: 'mortalKombat',
        format: 'Solo · bracket',
      }),
      ev({
        id: 'tekken',
        name: 'Tekken',
        tagline: 'Frame-perfect punishment',
        blurb: 'Classic iron-fist rules. Punish the whiff, close the round, take the set.',
        scene: 'tekken',
        format: 'Solo · bracket',
      }),
    ],
  },
  {
    id: 3,
    key: 'polygon',
    label: 'ERA 03',
    years: '1998 — 2007',
    category: 'Non-Technical',
    headline: 'POLYGON',
    description:
      'Games grew stories, soundtracks and side quests. So does the fest — the non-technical track is where personality outranks syntax.',
    accent: '#8b5cff',
    events: [
      ev({
        id: 'tech-tunes',
        name: 'Tech Tunes',
        tagline: 'Name that loading screen',
        blurb:
          'Audio rounds pulled from game scores, startup chimes and dial-up nostalgia. Buzz first, sing later.',
        scene: 'techTunes',
        format: 'Teams of 3 · 4 rounds',
      }),
      ev({
        id: 'the-parallel-protocol',
        name: 'The Parallel Protocol',
        tagline: 'Two worlds, one answer',
        blurb:
          'Paired teams solve mirrored halves of the same puzzle without seeing each other’s board.',
        scene: 'parallelProtocol',
        format: 'Teams of 4 · 60 min',
      }),
      ev({
        id: 'nexus-negotiator',
        name: 'Nexus Negotiator',
        tagline: 'Talk your way to the top',
        blurb:
          'A live negotiation ladder — alliances, trades and betrayals, scored on outcome and nerve.',
        scene: 'nexusNegotiator',
        format: 'Solo · 3 rounds',
      }),
      ev({
        id: 'array-pata-hai',
        name: 'Array Pata Hai',
        tagline: 'Charades for the terminally online',
        blurb: 'Act out the concept, guess the term, keep the streak alive down the row.',
        scene: 'arrayPataHai',
        format: 'Teams of 4 · 30 min',
      }),
      ev({
        id: 'secret-seekers',
        name: 'Secret Seekers',
        tagline: 'Campus-wide treasure hunt',
        blurb:
          'Chained clues across STME. Every lock has a key hidden in the last riddle you solved.',
        scene: 'secretSeekers',
        format: 'Teams of 4 · 90 min',
      }),
    ],
  },
  {
    id: 4,
    key: 'openworld',
    label: 'ERA 04',
    years: '2007 — 2018',
    category: 'Robotics · Media',
    headline: 'OPEN WORLD',
    description:
      'Physics engines, streamed worlds, capture pipelines. Hardware meets lens — machines that move and the crews that frame them.',
    accent: '#8b5cff',
    events: [
      ev({
        id: 'robo-soccer',
        name: 'Robo Soccer',
        tagline: 'Bots on the pitch',
        blurb:
          'Wired or wireless bots, two halves, one ball. Traction and control beat raw torque.',
        scene: 'roboSoccer',
        format: 'Teams of 4 · bracket',
      }),
      ev({
        id: 'robo-race',
        name: 'Robo Race',
        tagline: 'Obstacle sprint against the clock',
        blurb: 'Ramps, gravel, hairpins. Fastest clean run through the track takes the podium.',
        scene: 'roboRace',
        format: 'Teams of 4 · timed runs',
      }),
      ev({
        id: 'through-the-lens',
        name: 'Sidequest — Through the Lens',
        tagline: 'Photography sidequest',
        blurb:
          'A shot list drops at the start of the day. Fill it before the sun does, submit unedited.',
        scene: 'throughTheLens',
        format: 'Solo · all day',
      }),
      ev({
        id: 'quest-to-cinema',
        name: 'Quest to Cinema',
        tagline: '60-second film challenge',
        blurb: 'Prompt, shoot, cut and screen within the day. Sound design counts.',
        scene: 'questToCinema',
        format: 'Teams of 3 · all day',
      }),
      ev({
        id: 'interface-quest',
        name: 'Interface Quest',
        tagline: 'UI/UX design sprint',
        blurb:
          'Take a broken flow and redesign it for a real constraint. Defend it in a two-minute crit.',
        scene: 'interfaceQuest',
        format: 'Solo or duo · 120 min',
      }),
    ],
  },
  {
    id: 5,
    key: 'generated',
    label: 'ERA 05',
    years: '2018 — NOW',
    category: 'Next-Gen / AI',
    headline: 'GENERATED',
    description:
      'Worlds assembled on demand, assets dreamt by models, mechanics tuned by agents. The last era is the one still being written.',
    accent: '#4ce0ff',
    events: [
      ev({
        id: 'game-athon',
        name: 'Game-Athon',
        tagline: 'Build a playable game in a day',
        blurb:
          'Theme drops at 09:30. Ship something playable by 17:00 — engine, art and AI tooling all fair game.',
        scene: 'gameAthon',
        format: 'Teams of 4 · 7 hours',
      }),
    ],
  },
];

export const ALL_EVENTS = ERAS.flatMap((e) => e.events);

export function eraForEvent(slug: string): Era | undefined {
  return ERAS.find((era) => era.events.some((e) => e.slug === slug));
}

export function eventBySlug(slug: string): AnvikshaEvent | undefined {
  return ALL_EVENTS.find((e) => e.slug === slug);
}

/* ---------------------------------------------------------------------------
   RUN OF SHOW

   ⚠ STILL PLACEHOLDER. These 20 rows were authored to the correct shape as
   scaffolding; the real run-of-show has NOT landed in this file yet. Replace
   the array below, then flip SCHEDULE_IS_PLACEHOLDER to false — that single
   boolean removes the on-page warning banner. Nothing else needs to change.
   --------------------------------------------------------------------------- */
export const SCHEDULE_IS_PLACEHOLDER = true;

export interface ScheduleRow {
  time: string;
  slot: string;
  venue: string;
  track: string;
}

export const SCHEDULE: ScheduleRow[] = [
  { time: '08:30', slot: 'Registration & Kit Collection', venue: 'Main Foyer', track: 'ALL' },
  { time: '09:15', slot: 'Inauguration · Lighting of the Lamp', venue: 'Auditorium', track: 'ALL' },
  { time: '09:30', slot: 'Game-Athon — Theme Reveal', venue: 'Lab 204', track: 'NEXT-GEN' },
  { time: '10:00', slot: 'Capture the Flag · Round 1', venue: 'Lab 201', track: 'TECHNICAL' },
  { time: '10:00', slot: 'Valorant · Group Stage', venue: 'E-Sports Arena', track: 'E-SPORTS' },
  { time: '10:30', slot: 'Bridge Wars · Build Phase', venue: 'Workshop Bay', track: 'TECHNICAL' },
  { time: '11:00', slot: 'Tech Tunes · Prelims', venue: 'Seminar Hall A', track: 'NON-TECH' },
  { time: '11:30', slot: 'Robo Race · Qualifying Runs', venue: 'Central Quad', track: 'ROBOTICS' },
  { time: '12:00', slot: 'Escape the Server', venue: 'Lab 203', track: 'TECHNICAL' },
  { time: '12:30', slot: 'Lunch Break', venue: 'Cafeteria', track: 'ALL' },
  { time: '13:15', slot: 'Algorithm Auction', venue: 'Lab 202', track: 'TECHNICAL' },
  { time: '13:30', slot: 'Interface Quest · Design Sprint', venue: 'Studio 1', track: 'MEDIA' },
  { time: '14:00', slot: 'Robo Soccer · Knockouts', venue: 'Central Quad', track: 'ROBOTICS' },
  { time: '14:00', slot: 'Secret Seekers · Hunt Begins', venue: 'Campus-wide', track: 'NON-TECH' },
  { time: '14:30', slot: 'AI Whisperer', venue: 'Lab 205', track: 'TECHNICAL' },
  { time: '15:00', slot: 'Mortal Kombat · Tekken · FIFA Finals', venue: 'E-Sports Arena', track: 'E-SPORTS' },
  { time: '15:30', slot: 'Nexus Negotiator · Final Table', venue: 'Seminar Hall B', track: 'NON-TECH' },
  { time: '16:00', slot: 'Quest to Cinema · Screening', venue: 'Auditorium', track: 'MEDIA' },
  { time: '17:00', slot: 'Game-Athon · Submissions Close', venue: 'Lab 204', track: 'NEXT-GEN' },
  { time: '17:30', slot: 'Prize Distribution & Closing', venue: 'Auditorium', track: 'ALL' },
];

/* --- Derived event facts. One source of truth: `format` + SCHEDULE. -------- */

/** Second segment of `format` — "120 min", "bracket", "all day". */
export function eventDuration(event: AnvikshaEvent): string | null {
  const parts = event.format.split('·').map((s) => s.trim());
  return parts[1] || null;
}

/** First segment of `format` — the informal team shape shown on the card chip. */
export function eventFormatTeam(event: AnvikshaEvent): string | null {
  const parts = event.format.split('·').map((s) => s.trim());
  return parts[0] || null;
}

/** Strips the display prefix so "Sidequest — Through the Lens" matches a row. */
function scheduleNeedle(name: string) {
  return name.replace(/^sidequest\s*[—-]\s*/i, '').toLowerCase();
}

/** Schedule rows that mention this event, in run order. */
export function eventScheduleRows(event: AnvikshaEvent): ScheduleRow[] {
  const needle = scheduleNeedle(event.name);
  return SCHEDULE.filter((row) => row.slot.toLowerCase().includes(needle));
}

/** Venue from the run-of-show; null when no row mentions the event. */
export function eventVenue(event: AnvikshaEvent): string | null {
  return eventScheduleRows(event)[0]?.venue ?? null;
}

/** Start time from the run-of-show; null when no row mentions the event. */
export function eventStartTime(event: AnvikshaEvent): string | null {
  return eventScheduleRows(event)[0]?.time ?? null;
}

/* ---------------------------------------------------------------------------
   PRIZE POOL

   NEEDS DATA: `total` and every category `amount` below. While the headline
   total resolves to null the whole prize section does not render — no
   placeholder numbers ship.

   Per-event prizes live on the event objects (`prize`). `prizeFromEvents()`
   adds those up so the two can never drift: leave `total` null once every
   event carries a real prize and the section uses the computed sum instead.
   --------------------------------------------------------------------------- */
export interface PrizeCategory {
  /** Matches an Era `category`, or a custom bucket. */
  label: string;
  amount: number | null;
  note?: string;
}

export interface PrizePool {
  currency: string;
  /** Headline number. Null here falls back to the sum of per-event prizes. */
  total: number | null;
  categories: PrizeCategory[];
}

export const PRIZE_POOL: PrizePool = {
  currency: '₹',
  total: null, // NEEDS DATA: total prize pool
  categories: ERAS.map((era) => ({
    label: era.category,
    amount: null, // NEEDS DATA: per-track prize total
  })),
};

/** Sum of every confirmed per-event prize. Null when none are set yet. */
export function prizeFromEvents(): number | null {
  const known = ALL_EVENTS.map((e) => e.prize).filter((p): p is number => p !== null);
  return known.length ? known.reduce((a, b) => a + b, 0) : null;
}

/** Sum of confirmed per-event prizes for one track. */
export function prizeForCategory(category: string): number | null {
  const era = ERAS.find((e) => e.category === category);
  if (!era) return null;
  const known = era.events.map((e) => e.prize).filter((p): p is number => p !== null);
  return known.length ? known.reduce((a, b) => a + b, 0) : null;
}

/** The number the prize section actually renders. Null = section hidden. */
export function headlinePrizeTotal(): number | null {
  return PRIZE_POOL.total ?? prizeFromEvents();
}

/* ---------------------------------------------------------------------------
   COORDINATORS

   NEEDS DATA: the real coordinator list has NOT landed in this file. It is
   empty on purpose — the Credits section renders nothing rather than a grid
   of "??" cards. Add entries and the section appears, grouped by `group` in
   the order the groups first occur.

   Faculty: left out entirely until names are confirmed. Adding a single row
   with group 'Faculty' is all that is needed to bring that block back.
   --------------------------------------------------------------------------- */
export interface Coordinator {
  name: string;
  role: string;
  group: string;
  /** Optional — rendered as a mailto/tel chip when present. */
  contact?: string;
}

export const COORDINATORS: Coordinator[] = [
  // e.g. { name: 'A. Sharma', role: 'Fest Head', group: 'Core' },
];

/* ---------------------------------------------------------------------------
   FAQ

   Answers containing "[NEED:" are unconfirmed policy and render as a visibly
   flagged open question rather than an invented answer. Replace the bracket
   with the real answer and set `resolved: true`. Flip SHOW_UNRESOLVED_FAQS to
   false to hide every unresolved entry instead of publishing the brackets.
   --------------------------------------------------------------------------- */
export const SHOW_UNRESOLVED_FAQS = true;

export interface Faq {
  q: string;
  a: string;
  resolved: boolean;
}

export const FAQS: Faq[] = [
  {
    q: 'How do I register?',
    a: 'Registration runs through Unstop. Open any event from the Events section and use its “Register on Unstop” button — that takes you straight to the listing for that event. [NEED: confirm whether there is one fest-wide Unstop listing or a separate listing per event, and the master URL.]',
    resolved: false,
  },
  {
    q: 'Who can attend? Is it open to students from other colleges?',
    a: '[NEED: confirm eligibility — is ANVIKSHA open to all colleges, to NMIMS campuses only, or to STME students only? Also confirm whether non-participants may attend as spectators.]',
    resolved: false,
  },
  {
    q: 'Is there a registration fee?',
    a: '[NEED: confirm fee amount — a flat fest pass versus a per-event fee, and whether STME students are exempt.]',
    resolved: false,
  },
  {
    q: 'What is the team size?',
    a: 'It varies by event — some run solo, others in teams of two to five. Every event has its own team size listed on its page, so open the event from the Events section before you form a team. Where a size is not yet confirmed it is left off rather than guessed.',
    resolved: true,
  },
  {
    q: 'Can one person or team enter more than one event?',
    a: 'Yes. The fest is a single day and the run of show is built so most tracks do not collide — but check the schedule before committing to two events, because a few slots do overlap and the all-day formats (Game-Athon, the photography sidequest, Quest to Cinema) run across the whole day. [NEED: confirm whether there is a cap on how many events one participant may register for.]',
    resolved: false,
  },
  {
    q: 'Where is it, and how do I find my venue?',
    a: 'Everything runs on the STME campus at ' + FEST.venue + ', on ' + FEST.date + '. Each event’s venue is listed on its event page and in the run-of-show table. The registration desk in the Main Foyer opens before the first slot — start there and volunteers will point you to your room.',
    resolved: true,
  },
  {
    q: 'What should I bring?',
    a: 'A college ID, your registration confirmation, and a laptop with charger if your event needs one — the technical track and Game-Athon assume you are on your own machine. Robotics teams bring their own bot and spares. [NEED: confirm whether power and campus Wi-Fi are guaranteed at every venue, and whether robotics teams may charge batteries on site.]',
    resolved: false,
  },
  {
    q: 'Who do I contact for help?',
    a: 'Email the core team at ' + CONTACT_EMAIL + ', or reach us on Instagram — DMs are answered fastest on the day itself. On campus, the registration desk in the Main Foyer handles anything urgent.',
    resolved: true,
  },
];

/* ---------------------------------------------------------------------------
   SPONSORS

   NEEDS DATA: empty on purpose. The section is fully built and styled — add
   entries here and it renders; leave it empty and it does not appear at all.
   `logo` is inline SVG markup, not a file path: the site ships zero external
   assets, so a logo is pasted in as <svg>…</svg> source.
   --------------------------------------------------------------------------- */
export type SponsorTier = 'title' | 'gold' | 'silver' | 'media';

export interface Sponsor {
  name: string;
  tier: SponsorTier;
  url?: string;
  /** Inline SVG markup. No <img src> — the site ships zero external assets. */
  logo?: string;
}

export const SPONSOR_TIERS: { key: SponsorTier; label: string }[] = [
  { key: 'title', label: 'Title Partner' },
  { key: 'gold', label: 'Gold Partners' },
  { key: 'silver', label: 'Silver Partners' },
  { key: 'media', label: 'Media Partners' },
];

export const SPONSORS: Sponsor[] = [];

/* ---------------------------------------------------------------------------
   CONTACT & SOCIAL

   NEEDS DATA: every href below marked "-url-needed" is a deliberate, greppable
   placeholder. A social entry only renders as a live link once its href no
   longer contains that marker, so nothing broken ships in the meantime.
   Grep: rg -- "-url-needed"
   --------------------------------------------------------------------------- */
export const CONTACT = {
  email: CONTACT_EMAIL,
  /* NEEDS DATA: real handle, and phone number if there is a public one. */
  instagramHandle: null as string | null,
  phone: null as string | null,
} as const;

export type SocialKey = 'instagram' | 'linkedin' | 'youtube' | 'unstop' | 'email';

export interface Social {
  key: SocialKey;
  label: string;
  href: string;
  /** Pinned into the nav bar, not just the footer. */
  primary?: boolean;
}

export const SOCIALS: Social[] = [
  { key: 'instagram', label: 'Instagram', href: '#instagram-url-needed', primary: true },
  { key: 'linkedin', label: 'LinkedIn', href: '#linkedin-url-needed' },
  { key: 'youtube', label: 'YouTube', href: '#youtube-url-needed' },
  { key: 'unstop', label: 'Unstop', href: '#unstop-url-needed' },
  { key: 'email', label: 'Email', href: 'mailto:' + CONTACT_EMAIL },
];

/** True while an href is still a marked placeholder. */
export const isPlaceholderHref = (href: string) => href.includes('-url-needed');

/** Socials with a real destination. Placeholders never render as live links. */
export const liveSocials = () => SOCIALS.filter((s) => !isPlaceholderHref(s.href));
