/**
 * Single source of truth for every piece of copy on the site.
 *
 * BRANDING HIERARCHY (do not flatten this — see FEST below):
 *   1. ANVIKSHA '26 — THE EPOCH          the fest
 *   2. Digital Voyage: Charting the       the theme
 *      Course of Innovation
 *   3. "five eras of gaming, arcade       the VISUAL SYSTEM used to express
 *      to AI"                             the theme. Never billed as a theme.
 *
 * DATA GAPS: fields typed `| null` are awaiting real values. They are null on
 * purpose — every consumer omits the row entirely rather than printing "TBD".
 * Search this file for "NEEDS DATA" to find all of them.
 */

export type EraId = 1 | 2 | 3 | 4 | 5;

export type SceneKey =
  | 'captureTheFlag'
  | 'escapeTheServer'
  | 'bridgeWars'
  | 'algorithmAuction'
  | 'techMinute'
  | 'techTunes'
  | 'parallelProtocol'
  | 'nexusNegotiator'
  | 'arrayPataHai'
  | 'secretSeekers'
  | 'valorant'
  | 'fifa'
  | 'mortalKombat'
  | 'tekken'
  | 'roboSoccer'
  | 'roboRace'
  | 'throughTheLens'
  | 'questToCinema'
  | 'interfaceQuest'
  | 'gameAthon';

export interface AnvikshaEvent {
  id: string;
  /** URL segment: /events/<slug>. Kept identical to `id`. */
  slug: string;
  name: string;
  tagline: string;
  blurb: string;
  scene: SceneKey;
  /** Short chip copy, e.g. "Teams of 3 · 120 min". Duration is parsed from it. */
  format: string;

  /* --- NEEDS DATA: supplied per event, null until then ------------------- */
  /** Full rule set, one string per bullet. */
  rules: string[] | null;
  /** Confirmed team size, e.g. "3–4 members". */
  teamSize: string | null;
  /** Confirmed prize for this event, in rupees. Feeds the prize pool section. */
  prize: number | null;
  /** Direct Unstop registration URL for this event. */
  unstopUrl: string | null;
}

export interface Era {
  id: EraId;
  key: string;
  label: string;
  years: string;
  category: string;
  headline: string;
  description: string;
  accent: string;
  events: AnvikshaEvent[];
}

/* Every event literal below omits the four gap fields; this fills them with
   null so the type stays honest without repeating `rules: null` 21 times. */
type EventSeed = Omit<AnvikshaEvent, 'slug' | 'rules' | 'teamSize' | 'prize' | 'unstopUrl'> &
  Partial<Pick<AnvikshaEvent, 'rules' | 'teamSize' | 'prize' | 'unstopUrl'>>;

const ev = (seed: EventSeed): AnvikshaEvent => ({
  slug: seed.id,
  rules: null,
  teamSize: null,
  prize: null,
  unstopUrl: null,
  ...seed,
});

export const FEST = {
  name: "ANVIKSHA '26",
  subtitle: 'The Epoch',

  /** The theme. The only thing that should ever be labelled "theme". */
  theme: 'Digital Voyage: Charting the Course of Innovation',

  /** Subtitle to the theme — the visual system, introduced once. */
  themeSubtitle: 'Charted across five eras of gaming, from arcade to AI.',

  /** Same idea in plain language, for the About section. */
  themePlain:
    'Innovation does not arrive all at once — it is charted, one leap at a time. Digital Voyage follows that route, and we tell it through the medium every engineer grew up with: five eras of gaming, from the first arcade cabinet to worlds generated by machines.',

  date: '12 September 2026',
  dateShort: '12.09.2026',
  /** Countdown target — 09:30 IST. */
  startsAtISO: '2026-09-12T09:30:00+05:30',
  /** Used only to switch the countdown from "Live Now" to "Concluded". */
  endsAtISO: '2026-09-12T18:30:00+05:30',

  venue: 'STME, NMIMS Chandigarh',
  venueShort: 'STME NMIMS Chandigarh',
  institute: 'School of Technology Management & Engineering',
  university: 'NMIMS Chandigarh',

  edition: '2026 edition',
  /** Previous editions, newest last. Drives the About copy. */
  pastEditions: ['2024', '2025'],
  cadence: 'Single-day',

  /** Fest-wide Unstop listing. This is the GENERAL "Register Now" target —
      nav CTA, hero, the closing insert-coin button. Individual events use
      their own `unstopUrl` instead; never point an event card here. */
  registerUrl:
    'https://unstop.com/college-fests/anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-507675',

  /** Google Drive folder holding every event brochure and rule sheet.
      SHARED, NOT PER-EVENT: the root folder is the only Drive link supplied,
      so every event's "More Details" button points here too. Drive folder IDs
      are opaque and cannot be derived from an event name, so per-event deep
      links stay unwired until the 21 individual URLs land. Add an optional
      `brochureUrl` to AnvikshaEvent at that point and the detail view will
      prefer it — see EventDetail. */
  brochureUrl: 'https://drive.google.com/drive/u/5/folders/1W2LqWQBN0L4S7ENPJ15eJ8pTJpDIYPY5',

  /** Registration partner. The "Powered by Unstop" tag credits the partner and
      therefore points at unstop.com, NOT at the fest listing — `registerUrl`
      above is the listing, and the two must not be conflated: a credit that
      silently became a fourth Register CTA would be a dark pattern. */
  partner: 'Unstop',
  partnerUnstopUrl: 'https://unstop.com',

  brief:
    'One day. Five eras. ANVIKSHA 26 traces the arc of play from the phosphor glow of the first arcade cabinet to worlds generated on the fly by machines — and asks what engineers build next.',
} as const;

export const ERAS: Era[] = [
  {
    id: 1,
    key: 'arcade',
    label: 'ERA 01',
    years: '1972 — 1985',
    category: 'Technical',
    headline: 'PHOSPHOR',
    description:
      'Blocky sprites, one screen, no save file. Pure logic under hard constraints — which is exactly what the technical track asks of you.',
    accent: '#39ff6a',
    events: [
      ev({
        id: 'capture-the-flag',
        name: 'Capture the Flag',
        tagline: 'Jeopardy-style security gauntlet',
        blurb:
          'Crack layered challenges across crypto, forensics and web exploitation. Every flag planted is points on the board.',
        scene: 'captureTheFlag',
        format: 'Teams of 3 · 120 min',
        unstopUrl:
          'https://unstop.com/p/capture-the-flag-operation-zero-trace-duplicate-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies--1745175',
      }),
      ev({
        id: 'escape-the-server',
        name: 'Escape the Server',
        tagline: 'Locked in a rack, ticking clock',
        blurb:
          'A chained set of systems puzzles — logs, ports, permissions. Solve the sequence before the vault seals for good.',
        scene: 'escapeTheServer',
        format: 'Teams of 4 · 60 min',
        unstopUrl:
          'https://unstop.com/p/escape-the-server-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745480',
      }),
      ev({
        id: 'bridge-wars',
        name: 'Bridge Wars',
        tagline: 'Load-bearing engineering under pressure',
        blurb:
          'Design, build and test a truss that survives the load run. Least material, most strength, wins.',
        scene: 'bridgeWars',
        format: 'Teams of 3 · 90 min',
        unstopUrl:
          'https://unstop.com/p/bridge-wars-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745431',
      }),
      ev({
        id: 'algorithm-auction',
        name: 'Algorithm Auction',
        tagline: 'Bid for the code you need',
        blurb:
          'Spend a virtual purse on algorithm fragments, then assemble them into the fastest working solution. Bad bids cost you complexity.',
        scene: 'algorithmAuction',
        format: 'Teams of 2 · 75 min',
        unstopUrl:
          'https://unstop.com/p/algorithm-auction-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745434',
      }),
      ev({
        id: 'tech-minute-to-win-it',
        name: 'Tech Minute to Win It',
        tagline: 'Sixty seconds per station',
        blurb:
          'Rapid-fire micro-challenges: debug it, wire it, name it, ship it. The clock is the only judge that matters.',
        scene: 'techMinute',
        format: 'Solo · rolling heats',
        unstopUrl:
          'https://unstop.com/p/tech-minute-to-win-it-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745437',
      }),
    ],
  },
  {
    id: 2,
    key: 'cabinet',
    label: 'ERA 02',
    years: '1985 — 1998',
    category: 'E-Sports',
    headline: 'CABINET',
    description:
      'Neon cabinets, quarter-fed rivalries, the first crowds around a screen. The competitive instinct that built e-sports starts here.',
    accent: '#ff2e7e',
    events: [
      ev({
        id: 'valorant',
        name: 'Valorant',
        tagline: '5v5 tactical shooter',
        blurb: 'Standard competitive map pool, single-elimination bracket, BO1 until the semis.',
        scene: 'valorant',
        format: 'Teams of 5 · bracket',
        unstopUrl:
          'https://unstop.com/p/valorant-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745176',
      }),
      ev({
        id: 'fifa',
        name: 'FIFA',
        tagline: 'One-on-one on the pitch',
        blurb: 'Six-minute halves, no custom squads, golden goal in the knockouts.',
        scene: 'fifa',
        format: 'Solo · bracket',
        unstopUrl:
          'https://unstop.com/p/fifa-25-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745179',
      }),
      ev({
        id: 'mortal-kombat',
        name: 'Mortal Kombat',
        tagline: 'Best of three, no mercy',
        blurb: 'Blind character select, first to two rounds, winner stays on the stick.',
        scene: 'mortalKombat',
        format: 'Solo · bracket',
        unstopUrl:
          'https://unstop.com/p/mortal-kombat-1-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745184',
      }),
      ev({
        id: 'tekken',
        name: 'Tekken',
        tagline: 'Frame-perfect punishment',
        blurb: 'Classic iron-fist rules. Punish the whiff, close the round, take the set.',
        scene: 'tekken',
        format: 'Solo · bracket',
        unstopUrl:
          'https://unstop.com/p/tekken-8-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745181',
      }),
    ],
  },
  {
    id: 3,
    key: 'polygon',
    label: 'ERA 03',
    years: '1998 — 2007',
    category: 'Non-Technical',
    headline: 'POLYGON',
    description:
      'Games grew stories, soundtracks and side quests. So does the fest — the non-technical track is where personality outranks syntax.',
    accent: '#8b5cff',
    events: [
      ev({
        id: 'tech-tunes',
        name: 'Tech Tunes',
        tagline: 'Name that loading screen',
        blurb:
          'Audio rounds pulled from game scores, startup chimes and dial-up nostalgia. Buzz first, sing later.',
        scene: 'techTunes',
        format: 'Teams of 3 · 4 rounds',
        unstopUrl:
          'https://unstop.com/p/tech-tunes-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745121',
      }),
      ev({
        id: 'the-parallel-protocol',
        name: 'The Parallel Protocol',
        tagline: 'Two worlds, one answer',
        blurb:
          'Paired teams solve mirrored halves of the same puzzle without seeing each other’s board.',
        scene: 'parallelProtocol',
        format: 'Teams of 4 · 60 min',
        unstopUrl:
          'https://unstop.com/p/the-parallel-protocol-duplicate-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745173',
      }),
      ev({
        id: 'nexus-negotiator',
        name: 'Nexus Negotiator',
        tagline: 'Talk your way to the top',
        blurb:
          'A live negotiation ladder — alliances, trades and betrayals, scored on outcome and nerve.',
        scene: 'nexusNegotiator',
        format: 'Solo · 3 rounds',
        unstopUrl:
          'https://unstop.com/p/nexus-negotiator-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745142',
      }),
      ev({
        id: 'array-pata-hai',
        name: 'Array Pata Hai',
        tagline: 'Charades for the terminally online',
        blurb: 'Act out the concept, guess the term, keep the streak alive down the row.',
        scene: 'arrayPataHai',
        format: 'Teams of 4 · 30 min',
        unstopUrl:
          'https://unstop.com/p/array-pata-hai-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745167',
      }),
      ev({
        id: 'secret-seekers',
        name: 'Secret Seekers',
        tagline: 'Campus-wide treasure hunt',
        blurb:
          'Chained clues across STME. Every lock has a key hidden in the last riddle you solved.',
        scene: 'secretSeekers',
        format: 'Teams of 4 · 90 min',
        unstopUrl:
          'https://unstop.com/p/secret-seekers-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745169',
      }),
    ],
  },
  {
    id: 4,
    key: 'openworld',
    label: 'ERA 04',
    years: '2007 — 2018',
    category: 'Robotics · Media',
    headline: 'OPEN WORLD',
    description:
      'Physics engines, streamed worlds, capture pipelines. Hardware meets lens — machines that move and the crews that frame them.',
    accent: '#8b5cff',
    events: [
      ev({
        id: 'robo-soccer',
        name: 'Robo Soccer',
        tagline: 'Bots on the pitch',
        blurb:
          'Wired or wireless bots, two halves, one ball. Traction and control beat raw torque.',
        scene: 'roboSoccer',
        format: 'Teams of 4 · bracket',
        unstopUrl:
          'https://unstop.com/p/robo-soccer-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745193',
      }),
      ev({
        id: 'robo-race',
        name: 'Robo Race',
        tagline: 'Obstacle sprint against the clock',
        blurb: 'Ramps, gravel, hairpins. Fastest clean run through the track takes the podium.',
        scene: 'roboRace',
        format: 'Teams of 4 · timed runs',
        unstopUrl:
          'https://unstop.com/p/robo-race-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745186',
      }),
      ev({
        id: 'through-the-lens',
        name: 'Sidequest — Through the Lens',
        tagline: 'Photography sidequest',
        blurb:
          'A shot list drops at the start of the day. Fill it before the sun does, submit unedited.',
        scene: 'throughTheLens',
        format: 'Solo · all day',
        unstopUrl:
          'https://unstop.com/events/side-questing-sidequest-through-the-lens-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nm-1745444',
      }),
      ev({
        id: 'quest-to-cinema',
        name: 'Quest to Cinema',
        tagline: '60-second film challenge',
        blurb: 'Prompt, shoot, cut and screen within the day. Sound design counts.',
        scene: 'questToCinema',
        format: 'Teams of 3 · all day',
        unstopUrl:
          'https://unstop.com/events/quest-to-cinema-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745441',
      }),
      ev({
        id: 'interface-quest',
        name: 'Interface Quest',
        tagline: 'UI/UX design sprint',
        blurb:
          'Take a broken flow and redesign it for a real constraint. Defend it in a two-minute crit.',
        scene: 'interfaceQuest',
        format: 'Solo or duo · 120 min',
        unstopUrl:
          'https://unstop.com/events/interface-quest-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745442',
      }),
    ],
  },
  {
    id: 5,
    key: 'generated',
    label: 'ERA 05',
    years: '2018 — NOW',
    category: 'Next-Gen / AI',
    headline: 'GENERATED',
    description:
      'Worlds assembled on demand, assets dreamt by models, mechanics tuned by agents. The last era is the one still being written.',
    accent: '#4ce0ff',
    events: [
      ev({
        id: 'game-athon',
        name: 'Game-Athon',
        tagline: 'Build a playable game in a day',
        blurb:
          'Theme drops at 09:30. Ship something playable by 17:00 — engine, art and AI tooling all fair game.',
        scene: 'gameAthon',
        format: 'Teams of 4 · 7 hours',
        unstopUrl:
          'https://unstop.com/hackathons/game-athon-anviksha-the-epoch-2026-narsee-monjee-institute-of-management-studies-nmims-chandigarh-1745439',
      }),
    ],
  },
];

export const ALL_EVENTS = ERAS.flatMap((e) => e.events);

export function eraForEvent(slug: string): Era | undefined {
  return ERAS.find((era) => era.events.some((e) => e.slug === slug));
}

export function eventBySlug(slug: string): AnvikshaEvent | undefined {
  return ALL_EVENTS.find((e) => e.slug === slug);
}

/* ---------------------------------------------------------------------------
   RUN OF SHOW

   PARTLY CONFIRMED. The twelve event rows marked "confirmed" below carry the
   real windows supplied by the committee — Non-Technical, Technical and Robo
   Club. Everything else (registration, inauguration, the lunch break, the
   e-sports bracket, the media slots and the closing ceremony) is still the
   original scaffolding, which is why SCHEDULE_IS_PLACEHOLDER stays true and
   the on-page notice stays up. Flip it to false once those rows land too.

   VENUES ARE NOT CONFIRMED for any row. The rooms below are scaffolding, and
   the three rows added with the confirmed timings (The Parallel Protocol,
   Array Pata Hai, Tech Minute to Win It) were given rooms that do not collide
   with anything else running at the same time — but no venue here should be
   printed on a poster until the committee supplies the real allocation.

   `time` is the START, and it is the only field the timeline lays out on:
   lib/timeline.ts derives every block's vertical position from it, so editing
   a time here moves the block. Nothing about the staircase is positioned by
   hand. `end` is optional and display-only.
   --------------------------------------------------------------------------- */
export const SCHEDULE_IS_PLACEHOLDER = true;

export interface ScheduleRow {
  /** Start time, 24h "HH:MM". Drives the timeline's vertical layout. */
  time: string;
  /** End time, where a confirmed window exists. Display only. */
  end?: string;
  slot: string;
  venue: string;
  track: string;
}

export const SCHEDULE: ScheduleRow[] = [
  { time: '08:30', slot: 'Registration & Kit Collection', venue: 'Main Foyer', track: 'ALL' },
  { time: '09:15', slot: 'Inauguration · Lighting of the Lamp', venue: 'Auditorium', track: 'ALL' },
  { time: '09:30', slot: 'Game-Athon — Theme Reveal', venue: 'Lab 204', track: 'NEXT-GEN' },

  /* --- confirmed windows ------------------------------------------------- */
  { time: '10:00', end: '12:30', slot: 'Bridge Wars', venue: 'Workshop Bay', track: 'TECHNICAL' },
  { time: '10:00', slot: 'Valorant · Group Stage', venue: 'E-Sports Arena', track: 'E-SPORTS' },
  { time: '10:30', end: '16:30', slot: 'Robo Race', venue: 'Central Quad A', track: 'ROBOTICS' },
  { time: '10:30', end: '16:30', slot: 'Robo Soccer', venue: 'Central Quad B', track: 'ROBOTICS' },
  { time: '11:00', end: '14:00', slot: 'Tech Tunes', venue: 'Seminar Hall A', track: 'NON-TECH' },
  { time: '11:00', end: '13:00', slot: 'The Parallel Protocol', venue: 'Seminar Hall B', track: 'NON-TECH' },
  { time: '11:30', end: '12:30', slot: 'Tech Minute to Win It', venue: 'Lab 206', track: 'TECHNICAL' },
  { time: '11:30', end: '13:00', slot: 'Capture the Flag', venue: 'Lab 201', track: 'TECHNICAL' },
  { time: '12:00', end: '14:00', slot: 'Nexus Negotiator', venue: 'Seminar Hall C', track: 'NON-TECH' },
  { time: '12:00', end: '14:00', slot: 'Array Pata Hai', venue: 'Lab 205', track: 'NON-TECH' },
  { time: '12:30', slot: 'Lunch Break', venue: 'Cafeteria', track: 'ALL' },
  { time: '13:00', end: '15:00', slot: 'Secret Seekers', venue: 'Campus-wide', track: 'NON-TECH' },
  { time: '13:00', end: '14:30', slot: 'Escape the Server', venue: 'Lab 203', track: 'TECHNICAL' },
  { time: '13:30', slot: 'Interface Quest · Design Sprint', venue: 'Studio 1', track: 'MEDIA' },
  { time: '14:30', end: '16:00', slot: 'Algorithm Auction', venue: 'Lab 202', track: 'TECHNICAL' },
  /* ----------------------------------------------------------------------- */

  { time: '15:00', slot: 'Mortal Kombat · Tekken · FIFA Finals', venue: 'E-Sports Arena', track: 'E-SPORTS' },
  { time: '16:00', slot: 'Quest to Cinema · Screening', venue: 'Auditorium', track: 'MEDIA' },
  { time: '17:00', slot: 'Game-Athon · Submissions Close', venue: 'Lab 204', track: 'NEXT-GEN' },
  { time: '17:30', slot: 'Prize Distribution & Closing', venue: 'Auditorium', track: 'ALL' },
];

/** "10:30 – 16:30", or just the start when no end is confirmed. */
export function scheduleRange(row: ScheduleRow, dash = '–'): string {
  return row.end ? `${row.time} ${dash} ${row.end}` : row.time;
}

/* --- Derived event facts. One source of truth: `format` + SCHEDULE. -------- */

/** Second segment of `format` — "120 min", "bracket", "all day". */
export function eventDuration(event: AnvikshaEvent): string | null {
  const parts = event.format.split('·').map((s) => s.trim());
  return parts[1] || null;
}

/** First segment of `format` — the informal team shape shown on the card chip. */
export function eventFormatTeam(event: AnvikshaEvent): string | null {
  const parts = event.format.split('·').map((s) => s.trim());
  return parts[0] || null;
}

/** Strips the display prefix so "Sidequest — Through the Lens" matches a row. */
function scheduleNeedle(name: string) {
  return name.replace(/^sidequest\s*[—-]\s*/i, '').toLowerCase();
}

/** Schedule rows that mention this event, in run order. */
export function eventScheduleRows(event: AnvikshaEvent): ScheduleRow[] {
  const needle = scheduleNeedle(event.name);
  return SCHEDULE.filter((row) => row.slot.toLowerCase().includes(needle));
}

/** Venue from the run-of-show; null when no row mentions the event. */
export function eventVenue(event: AnvikshaEvent): string | null {
  return eventScheduleRows(event)[0]?.venue ?? null;
}

/** Start time from the run-of-show; null when no row mentions the event. */
export function eventStartTime(event: AnvikshaEvent): string | null {
  return eventScheduleRows(event)[0]?.time ?? null;
}

/* ---------------------------------------------------------------------------
   PRIZE POOL

   NEEDS DATA: `total` and every category `amount` below. While the headline
   total resolves to null the whole prize section does not render — no
   placeholder numbers ship.

   Per-event prizes live on the event objects (`prize`). `prizeFromEvents()`
   adds those up so the two can never drift: leave `total` null once every
   event carries a real prize and the section uses the computed sum instead.
   --------------------------------------------------------------------------- */
export interface PrizeCategory {
  /** Matches an Era `category`, or a custom bucket. */
  label: string;
  amount: number | null;
  note?: string;
}

export interface PrizePool {
  currency: string;
  /** Headline number. Null here falls back to the sum of per-event prizes. */
  total: number | null;
  categories: PrizeCategory[];
}

export const PRIZE_POOL: PrizePool = {
  currency: '₹',
  total: null, // NEEDS DATA: total prize pool
  categories: ERAS.map((era) => ({
    label: era.category,
    amount: null, // NEEDS DATA: per-track prize total
  })),
};

/** Sum of every confirmed per-event prize. Null when none are set yet. */
export function prizeFromEvents(): number | null {
  const known = ALL_EVENTS.map((e) => e.prize).filter((p): p is number => p !== null);
  return known.length ? known.reduce((a, b) => a + b, 0) : null;
}

/** Sum of confirmed per-event prizes for one track. */
export function prizeForCategory(category: string): number | null {
  const era = ERAS.find((e) => e.category === category);
  if (!era) return null;
  const known = era.events.map((e) => e.prize).filter((p): p is number => p !== null);
  return known.length ? known.reduce((a, b) => a + b, 0) : null;
}

/** The number the prize section actually renders. Null = section hidden. */
export function headlinePrizeTotal(): number | null {
  return PRIZE_POOL.total ?? prizeFromEvents();
}

/* ---------------------------------------------------------------------------
   THE COMMITTEE

   Two tables, joined by name — NOT one hand-written list per committee.

   PEOPLE is the per-person record: photo and LinkedIn live there exactly once.
   COMMITTEE_ROSTER is membership and nothing else. Three people sit on two
   committees each (Reetpal Kaur, Devanshu Juneja, Gauri Dhiman), so a flat
   per-committee list would carry their photo and URL twice and let the two
   copies drift. Here they render in both places from the single record.

   `photo` and `linkedin` are both OPTIONAL. All 38 members currently have
   both, so no fallback is visible on the live site — but the shape and the
   markup already handle their absence (initials avatar, and the name as plain
   text rather than a dead link), so a future roster change is a data edit and
   not a markup rewrite.

   `photo` is a filename in public/team, quoted exactly as delivered. Several
   do not match the member's official spelling — "Sia.jpeg" for Siya Nagpal,
   "Harkeerat.jpeg" for Harkirat Kaur, "Aashna.jpeg" for Ashna Bansal — and
   "Siddhant .jpeg" carries an interior space. They are NOT normalised: the
   filename is what is on disk, `name` is what a visitor reads, and fuzzy
   matching between the two is exactly the bug this table exists to prevent.

   Faculty: left out entirely until names are confirmed. Adding a group here is
   all that is needed to bring that block back.
   --------------------------------------------------------------------------- */
export interface TeamMember {
  name: string;
  /** Committee this listing belongs to. A person can appear in more than one. */
  committee: string;
  /** Filename in public/team. Absent -> initials avatar. */
  photo?: string;
  /** Absent -> the name renders as plain text, never as a dead link. */
  linkedin?: string;
}

interface PersonRecord {
  photo?: string;
  linkedin?: string;
}

/** One record per person, keyed by the name shown on the card. */
const PEOPLE: Record<string, PersonRecord> = {
  'Armaan Singh Sandhu': {
    photo: 'Armaan President.jpeg',
    linkedin: 'https://www.linkedin.com/in/armaan-singh-sandhu-831525326',
  },
  'Konark Jetly': {
    photo: 'Konark.jpeg',
    linkedin: 'https://www.linkedin.com/in/konark-jetly-150275143',
  },
  'Mannat Walia': {
    photo: 'Mannat.jpeg',
    linkedin: 'https://www.linkedin.com/in/mannat-walia-877899335',
  },
  'Madhav Prakash': {
    photo: 'Madhav.jpeg',
    linkedin: 'https://www.linkedin.com/in/madhav-prakash-3a593a1ab',
  },
  'Harshit Sharma': {
    photo: 'Harshit.jpeg',
    linkedin: 'https://www.linkedin.com/in/harshit-sharma-41b9b4269',
  },
  'Aaravdeep Gujral': {
    photo: 'Aaravdeep Singh Gujral.jpeg',
    linkedin: 'https://www.linkedin.com/in/aaravdeep-gujral-a2ab5b31b',
  },
  'Raghav Singla': {
    photo: 'Raghav Sponsorships.jpeg',
    linkedin: 'https://www.linkedin.com/in/raghav-singla-04764a432',
  },
  'Devanshu Juneja': {
    photo: 'Devanshu.jpeg',
    linkedin: 'https://www.linkedin.com/in/devanshujuneja',
  },
  'Reetpal Kaur': {
    photo: 'Reetpal Kaur.jpeg',
    linkedin: 'https://www.linkedin.com/in/reetpal-kaur-44097631a',
  },
  'Pulkit Mahajan': {
    photo: 'Pulkit.jpeg',
    linkedin: 'https://www.linkedin.com/in/pulkit-mahajan-a43884320',
  },
  'Soumya Sharma': {
    photo: 'Soumya.jpeg',
    linkedin: 'https://www.linkedin.com/in/soumya-sharma-3ab74b211',
  },
  'Siya Nagpal': {
    photo: 'Sia.jpeg',
    linkedin: 'https://www.linkedin.com/in/siya-nagpal-34564421b',
  },
  'Himanshi Farah': {
    photo: 'Himanshi.jpeg',
    linkedin: 'https://www.linkedin.com/in/himanshi-farah-55a652328',
  },
  'Harkirat Kaur': {
    photo: 'Harkeerat.jpeg',
    linkedin: 'https://www.linkedin.com/in/harkirat-kaur-248a40319',
  },
  'Gauri Dhiman': {
    photo: 'Gauri.jpeg',
    linkedin: 'https://www.linkedin.com/in/gauri-dhiman-6b8109342',
  },
  'Vanika Aggarwal': {
    photo: 'Vanika.jpeg',
    linkedin: 'https://www.linkedin.com/in/vanika-aggarwal-58a64b274',
  },
  'Palaksh Pandit': {
    photo: 'Palaksh.jpeg',
    linkedin: 'https://www.linkedin.com/in/palaksh-pandit-66a7773ab',
  },
  'Rishabh Jain': {
    photo: 'Rishabh.jpeg',
    linkedin: 'https://www.linkedin.com/in/rishabh-jain-b7665431a',
  },
  'Vinayak Goyal': {
    photo: 'Vinayak Robo Club.jpeg',
    linkedin: 'https://www.linkedin.com/in/vinayak-goyal-09971531a',
  },
  'Raghav Gandhi': {
    photo: 'Raghav Robo club.jpeg',
    linkedin: 'https://www.linkedin.com/in/raghav-gandhi-20070131a',
  },
  'Krish Rathi': {
    photo: 'Krish robo club.jpeg',
    linkedin: 'https://www.linkedin.com/in/krish-rathi-07665731a',
  },
  'Ranjot Singh': {
    photo: 'Ranjot.jpeg',
    linkedin: 'https://www.linkedin.com/in/ranjot-singh-8006ab31a',
  },
  'Tejus Midha': {
    photo: 'Tejus Midha.jpeg',
    linkedin: 'https://www.linkedin.com/in/tejus-midha',
  },
  'Aaryaman Manchanda': {
    photo: 'Aaryaman.jpeg',
    linkedin: 'http://www.linkedin.com/in/aaryaman-manchanda',
  },
  'Siddhant Rana': {
    photo: 'Siddhant .jpeg',
    linkedin: 'https://www.linkedin.com/in/siddhant-rana-703588361',
  },
  'Krrish Oberoi': {
    photo: 'Krrish Marketing.jpeg',
    linkedin: 'https://www.linkedin.com/in/krrish-oberoi-849b173a6',
  },
  'Shreya Hooda': {
    photo: 'Shreya.jpeg',
    linkedin: 'http://www.linkedin.com/in/shreya-hooda-9ab6163b3',
  },
  'Jayesh Mohan': {
    photo: 'Jayesh.jpeg',
    linkedin: 'https://www.linkedin.com/in/jayesh-mohan-3b6313264',
  },
  'Armaan Thakur': {
    photo: 'Armaan Registrations.jpeg',
    linkedin: 'https://www.linkedin.com/in/armaan-thakur-81a7a9297',
  },
  'Muskaan Mahajan': {
    photo: 'Muskaan.jpeg',
    linkedin: 'https://www.linkedin.com/in/muskaan-mahajan-0ab438369',
  },
  'Khyati Sharma': {
    photo: 'Khyati.jpeg',
    linkedin: 'https://www.linkedin.com/in/khyati-sharma-45a48831a',
  },
  'Ashna Bansal': {
    photo: 'Aashna.jpeg',
    linkedin: 'https://www.linkedin.com/in/ashna-bansal-a536b931a',
  },
  'Alvina Cs': {
    photo: 'Alvina.jpeg',
    linkedin: 'https://www.linkedin.com/in/alvina-cs',
  },
  'Avneet Kaur': {
    photo: 'Avneet.jpeg',
    linkedin: 'https://www.linkedin.com/in/avneet-kaur-1726ak',
  },
  'Saksham Thakur': {
    photo: 'Saksham.jpeg',
    linkedin: 'https://www.linkedin.com/in/saksham-thakur-2507752a3',
  },
  'Vinayak Datt': {
    photo: 'Vinayak Discipline.jpeg',
    linkedin: 'https://www.linkedin.com/in/vinayak-datt-081127311',
  },
  'Bhavyam Bhatnagar': {
    photo: 'Bhavyam.jpeg',
    linkedin: 'https://www.linkedin.com/in/bhavyam-bhatnagar-5601b5325',
  },
  'Eklavya Kapoor': {
    photo: 'Eklavya.jpeg',
    linkedin: 'http://www.linkedin.com/in/eklavya-kapoor',
  },
};

/** Membership only. Committees render top to bottom in this order. */
const COMMITTEE_ROSTER: [string, string[]][] = [
  ['Presidents', ['Armaan Singh Sandhu', 'Konark Jetly', 'Mannat Walia']],
  [
    'Sponsorships',
    [
      'Madhav Prakash',
      'Harshit Sharma',
      'Aaravdeep Gujral',
      'Raghav Singla',
      'Devanshu Juneja',
      'Reetpal Kaur',
    ],
  ],
  ['Technical', ['Pulkit Mahajan', 'Soumya Sharma']],
  ['Non-Technical', ['Siya Nagpal', 'Himanshi Farah', 'Harkirat Kaur']],
  ['Designing', ['Gauri Dhiman', 'Vanika Aggarwal']],
  ['E-Sports', ['Palaksh Pandit', 'Devanshu Juneja']],
  ['Robo Club', ['Rishabh Jain', 'Vinayak Goyal', 'Raghav Gandhi', 'Krish Rathi', 'Ranjot Singh']],
  ['Gameathon', ['Tejus Midha', 'Aaryaman Manchanda']],
  ['Photography', ['Gauri Dhiman']],
  ['Marketing', ['Siddhant Rana', 'Krrish Oberoi']],
  ['Hospitality', ['Shreya Hooda', 'Jayesh Mohan']],
  ['Registration', ['Armaan Thakur', 'Muskaan Mahajan']],
  ['Decoration', ['Reetpal Kaur', 'Khyati Sharma', 'Ashna Bansal', 'Alvina Cs', 'Avneet Kaur']],
  [
    'Discipline Committee',
    ['Saksham Thakur', 'Vinayak Datt', 'Bhavyam Bhatnagar', 'Eklavya Kapoor'],
  ],
];

export interface Committee {
  name: string;
  members: TeamMember[];
}

/** The join. A name with no PEOPLE record still renders — as initials and
    unlinked text — rather than throwing or being silently dropped. */
export const COMMITTEES: Committee[] = COMMITTEE_ROSTER.map(([name, names]) => ({
  name,
  members: names.map((person) => ({ name: person, committee: name, ...PEOPLE[person] })),
}));

/** Every listing, in render order. Someone on two committees appears twice. */
export const TEAM: TeamMember[] = COMMITTEES.flatMap((c) => c.members);

/** Distinct people. 38 today; three of them hold two seats. */
export const TEAM_PEOPLE: string[] = Object.keys(PEOPLE);

/** Public path for a committee photo. The image loader percent-encodes the
    spaces; the filename on disk is never rewritten to match a name. */
export function teamPhotoSrc(member: TeamMember): string | null {
  return member.photo ? `/team/${member.photo}` : null;
}

/** "Armaan Singh Sandhu" -> "AS". Only used when a photo is missing. */
export function initials(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (!parts.length) return '?';
  const first = parts[0][0];
  const last = parts.length > 1 ? parts[parts.length - 1][0] : '';
  return (first + last).toUpperCase();
}

/* ---------------------------------------------------------------------------
   FAQ

   SHOW_UNRESOLVED_FAQS is FALSE, which is the correct setting for a live,
   publicly-shared site: an entry with `resolved: false` is hidden entirely
   rather than published. A "[NEED: …]" bracket is an internal note to whoever
   is filling this file in — it must never reach a visitor, and with this flag
   off it cannot.

   Two answers below defer to the Unstop listing on purpose. Eligibility and
   fees are set per event and shown at the point of registration; neither is
   asserted here, because neither has been confirmed to this file. If a
   fest-wide rule is confirmed later, state it directly instead.
   --------------------------------------------------------------------------- */
export const SHOW_UNRESOLVED_FAQS = false;

export interface Faq {
  q: string;
  a: string;
  resolved: boolean;
}

export const FAQS: Faq[] = [
  {
    q: 'How do I register?',
    a: 'Registration runs through Unstop, and there are two ways in. “Register Now” anywhere on this site opens the fest-wide ANVIKSHA ’26 listing, where every event is in one place. Or open a single event from the Events section and use its “Register on Unstop” button, which goes straight to that event’s own listing. Each event’s brochure and full rule sheet are in the shared Drive folder linked from “Event Brochures & Rules”.',
    resolved: true,
  },
  {
    q: 'Who can attend? Is it open to students from other colleges?',
    a: 'Eligibility is set per event and is stated on that event’s Unstop listing — open the event from the Events section and check its listing before you register. If anything there is unclear, message us on Instagram or call one of the coordinators listed in the footer, and we will confirm.',
    resolved: true,
  },
  {
    q: 'Is there a registration fee?',
    a: 'Any fee is shown on the event’s Unstop listing at the point of registration, so you will see it before you commit. Open the event you want from the Events section to check.',
    resolved: true,
  },
  {
    q: 'What is the team size?',
    a: 'It varies by event — some run solo, others in teams of two to five. Every event has its own team size listed on its page, so open the event from the Events section before you form a team. Where a size is not yet confirmed it is left off rather than guessed.',
    resolved: true,
  },
  {
    q: 'Can one person or team enter more than one event?',
    a: 'Yes. The fest is a single day and the run of show is built so most tracks do not collide — but check the schedule before committing to two events, because a few slots do overlap and the all-day formats (Game-Athon, the photography sidequest, Quest to Cinema) run across the whole day.',
    resolved: true,
  },
  {
    q: 'Where is it, and how do I find my venue?',
    a: 'Everything runs on the STME campus at ' + FEST.venue + ', on ' + FEST.date + '. Each event’s venue is listed on its event page and in the run-of-show table. The registration desk in the Main Foyer opens before the first slot — start there and volunteers will point you to your room.',
    resolved: true,
  },
  {
    q: 'What should I bring?',
    a: 'A college ID, your registration confirmation, and a laptop with charger if your event needs one — the technical track and Game-Athon assume you are on your own machine. Robotics teams bring their own bot and spares.',
    resolved: true,
  },
  {
    q: 'Who do I contact for help?',
    a: 'Instagram is the fastest route — DMs are answered quickest on the day itself. The three coordinator numbers in the footer are there for anything urgent, and on campus the registration desk in the Main Foyer handles it.',
    resolved: true,
  },
];

/* ---------------------------------------------------------------------------
   SPONSORS

   NEEDS DATA: empty on purpose. The section is fully built and styled — add
   entries here and it renders; leave it empty and it does not appear at all.
   `logo` is inline SVG markup, not a file path: the site ships zero external
   assets, so a logo is pasted in as <svg>…</svg> source.
   --------------------------------------------------------------------------- */
export type SponsorTier = 'title' | 'gold' | 'silver' | 'media';

export interface Sponsor {
  name: string;
  tier: SponsorTier;
  url?: string;
  /** Inline SVG markup. No <img src> — the site ships zero external assets. */
  logo?: string;
}

export const SPONSOR_TIERS: { key: SponsorTier; label: string }[] = [
  { key: 'title', label: 'Title Partner' },
  { key: 'gold', label: 'Gold Partners' },
  { key: 'silver', label: 'Silver Partners' },
  { key: 'media', label: 'Media Partners' },
];

export const SPONSORS: Sponsor[] = [];

/* ---------------------------------------------------------------------------
   CONTACT & SOCIAL

   Instagram is the only social ANVIKSHA runs, so it is the only one listed —
   there is no LinkedIn/YouTube/Unstop handle to link, and an entry here that
   pointed nowhere would be worse than its absence.

   An href still carrying the greppable "-url-needed" marker renders as a
   disabled chip rather than a live link, so nothing broken can ship.
   Grep: rg -- "-url-needed"
   --------------------------------------------------------------------------- */
export interface ContactPerson {
  name: string;
  /** E.164, digits only after the +. `tel:` href is derived from this. */
  phone: string;
}

/** Phone contacts from the official contact card. Rendered in the footer. */
export const CONTACT_PEOPLE: ContactPerson[] = [
  { name: 'Konark Jetly', phone: '+916284892678' },
  { name: 'Armaan Singh Sandhu', phone: '+919815433450' },
  { name: 'Mannat Walia', phone: '+919988320006' },
];

/** "+916284892678" -> "+91 62848 92678". Display only; href uses the raw. */
export function formatPhone(phone: string): string {
  const m = phone.match(/^\+(\d{2})(\d{5})(\d{5})$/);
  return m ? `+${m[1]} ${m[2]} ${m[3]}` : phone;
}

/* NO FEST EMAIL EXISTS. There is no anviksha@ inbox, so none is published —
   a mailto: that bounces is worse than no address at all. The contact routes
   are Instagram and the three coordinator phone numbers above. If an inbox is
   set up later, add `email` here and the footer will render it. */
export const CONTACT = {
  instagramHandle: '@anviksha.nmimschd',
  people: CONTACT_PEOPLE,
} as const;

export type SocialKey = 'instagram' | 'linkedin' | 'youtube' | 'unstop' | 'email';

export interface Social {
  key: SocialKey;
  label: string;
  href: string;
  /** Shown next to the icon where the link is given room to breathe. */
  handle?: string;
  /** Pinned into the nav bar, not just the footer. */
  primary?: boolean;
}

export const SOCIALS: Social[] = [
  {
    key: 'instagram',
    label: 'Instagram',
    href: 'https://www.instagram.com/anviksha.nmimschd?utm_source=qr',
    handle: '@anviksha.nmimschd',
    primary: true,
  },
];

/** True while an href is still a marked placeholder. */
export const isPlaceholderHref = (href: string) => href.includes('-url-needed');

/** Socials with a real destination. Placeholders never render as live links. */
export const liveSocials = () => SOCIALS.filter((s) => !isPlaceholderHref(s.href));
